import { Category, Product, Coupon, Review, StoreSettings, Order } from '../types';

export const initialCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Electronics & Audio',
    slug: 'electronics-audio',
    description: 'Noise-cancelling headphones, smartwatches, fast chargers, and modern gadgets.',
    image_url: '/src/assets/images/category_tech_gadgets_1790526605221.jpg',
    is_active: true,
    created_at: new Date('2026-01-10').toISOString(),
    updated_at: new Date('2026-01-10').toISOString(),
  },
  {
    id: 'cat-2',
    name: 'Fashion & Apparel',
    slug: 'fashion-apparel',
    description: 'Premium textured linen shirts, casual jackets, and everyday modern apparel.',
    image_url: '/src/assets/images/category_apparel_fashion_1790526618915.jpg',
    is_active: true,
    created_at: new Date('2026-01-11').toISOString(),
    updated_at: new Date('2026-01-11').toISOString(),
  },
  {
    id: 'cat-3',
    name: 'Home & Living',
    slug: 'home-living',
    description: 'Minimalist ceramics, architectural table lamps, and tactile organic decor.',
    image_url: '/src/assets/images/category_home_living_1790526633926.jpg',
    is_active: true,
    created_at: new Date('2026-01-12').toISOString(),
    updated_at: new Date('2026-01-12').toISOString(),
  },
  {
    id: 'cat-4',
    name: 'Footwear & Sneaker',
    slug: 'footwear-sneakers',
    description: 'Handcrafted leather loafers, cushioned running sneakers, and casual boots.',
    image_url: '/src/assets/images/hero_ali_store_showcase_1790526590148.jpg',
    is_active: true,
    created_at: new Date('2026-01-14').toISOString(),
    updated_at: new Date('2026-01-14').toISOString(),
  },
  {
    id: 'cat-5',
    name: 'Watches & Accessories',
    slug: 'watches-accessories',
    description: 'Classic chronographs, leather wallets, and everyday luxury carry.',
    image_url: '/src/assets/images/hero_ali_store_showcase_1790526590148.jpg',
    is_active: true,
    created_at: new Date('2026-01-15').toISOString(),
    updated_at: new Date('2026-01-15').toISOString(),
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Apex Studio Wireless Headphones',
    slug: 'apex-studio-wireless-headphones',
    description: 'Engineered for audio purists with custom 40mm beryllium drivers, active hybrid noise cancellation, and 45-hour battery stamina. Wrapped in supple memory foam earcups with matte graphite finish.',
    short_description: 'Hybrid ANC, 40mm custom drivers, 45h stamina.',
    sku: 'ALI-AUD-001',
    brand: 'Apex Audio',
    price: 18500,
    discount_price: 15999,
    category_id: 'cat-1',
    stock_quantity: 24,
    low_stock_threshold: 5,
    is_active: true,
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: false,
    rating: 4.9,
    review_count: 28,
    variants: ['Matte Black', 'Sandstone Grey', 'Midnight Navy'],
    specifications: {
      'Bluetooth Version': '5.3 with LDAC support',
      'Battery Life': 'Up to 45 hours (ANC on)',
      'Weight': '250g',
      'Charging': 'USB-C fast charge (10 min = 5 hours)',
    },
    images: [
      {
        id: 'img-1-1',
        product_id: 'prod-1',
        image_url: '/src/assets/images/category_tech_gadgets_1790526605221.jpg',
        alt_text: 'Apex Studio Wireless Headphones in Matte Black',
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date('2026-01-15').toISOString(),
    updated_at: new Date('2026-01-15').toISOString(),
  },
  {
    id: 'prod-2',
    name: 'Vanguard Chronograph Classic Watch',
    slug: 'vanguard-chronograph-classic-watch',
    description: 'Precision Japanese quartz movement housed in 316L surgical-grade stainless steel casing with sapphire crystal glass and genuine Italian calfskin strap.',
    short_description: 'Sapphire crystal, 316L steel, Italian leather strap.',
    sku: 'ALI-WTC-002',
    brand: 'Vanguard Horology',
    price: 24000,
    discount_price: 19500,
    category_id: 'cat-5',
    stock_quantity: 12,
    low_stock_threshold: 4,
    is_active: true,
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: false,
    rating: 4.8,
    review_count: 19,
    variants: ['Silver / Cognac', 'Black / Black', 'Rose Gold / Espresso'],
    specifications: {
      'Case Diameter': '41mm',
      'Water Resistance': '50 meters / 5 ATM',
      'Movement': 'Miyota Chronograph Quartz',
      'Glass': 'Anti-reflective Sapphire Crystal',
    },
    images: [
      {
        id: 'img-2-1',
        product_id: 'prod-2',
        image_url: '/src/assets/images/hero_ali_store_showcase_1790526590148.jpg',
        alt_text: 'Vanguard Chronograph Classic Watch',
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date('2026-01-16').toISOString(),
    updated_at: new Date('2026-01-16').toISOString(),
  },
  {
    id: 'prod-3',
    name: 'Pure Linen Relaxed Overshirt',
    slug: 'pure-linen-relaxed-overshirt',
    description: 'Woven from 100% Normandy flax linen. Features natural mother-of-pearl buttons, twin chest patch pockets, and a tailored relaxed drop shoulder drape that softens with every wash.',
    short_description: '100% French linen, natural horn buttons, relaxed fit.',
    sku: 'ALI-APL-003',
    brand: 'Atelier Ali',
    price: 6800,
    discount_price: 5499,
    category_id: 'cat-2',
    stock_quantity: 38,
    low_stock_threshold: 8,
    is_active: true,
    is_featured: true,
    is_best_seller: false,
    is_new_arrival: true,
    rating: 4.7,
    review_count: 14,
    variants: ['Natural Ivory', 'Sage Olive', 'Washed Indigo'],
    specifications: {
      'Material': '100% Certified European Linen',
      'Fit': 'Relaxed unstructured cut',
      'Care': 'Machine wash cold on gentle, hang dry',
      'Origin': 'Ethically woven & crafted',
    },
    images: [
      {
        id: 'img-3-1',
        product_id: 'prod-3',
        image_url: '/src/assets/images/category_apparel_fashion_1790526618915.jpg',
        alt_text: 'Pure Linen Relaxed Overshirt in Ivory',
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date('2026-01-18').toISOString(),
    updated_at: new Date('2026-01-18').toISOString(),
  },
  {
    id: 'prod-4',
    name: 'Kyoto Ceramic Architectural Vase',
    slug: 'kyoto-ceramic-architectural-vase',
    description: 'Hand-thrown stoneware with textured unglazed exterior and sealed waterproof interior glaze. Asymmetrical silhouette designed to anchor minimalist dining tables or mantle displays.',
    short_description: 'Hand-thrown stoneware, textured matte stone finish.',
    sku: 'ALI-HOM-004',
    brand: 'Sora Ceramics',
    price: 5200,
    discount_price: 4400,
    category_id: 'cat-3',
    stock_quantity: 15,
    low_stock_threshold: 3,
    is_active: true,
    is_featured: true,
    is_best_seller: false,
    is_new_arrival: true,
    rating: 4.9,
    review_count: 11,
    variants: ['Chalk Off-White', 'Charcoal Basalt', 'Warm Sandstone'],
    specifications: {
      'Dimensions': '24cm height x 18cm diameter',
      'Material': 'High-fire stoneware ceramic',
      'Finish': 'Matte tactile exterior',
      'Weight': '1.4 kg',
    },
    images: [
      {
        id: 'img-4-1',
        product_id: 'prod-4',
        image_url: '/src/assets/images/category_home_living_1790526633926.jpg',
        alt_text: 'Kyoto Ceramic Architectural Vase',
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date('2026-01-20').toISOString(),
    updated_at: new Date('2026-01-20').toISOString(),
  },
  {
    id: 'prod-5',
    name: 'Titan Smart Pulse Titanium Watch',
    slug: 'titan-smart-pulse-titanium-watch',
    description: 'Aerospace grade titanium casing with 1.4-inch AMOLED display, sapphire dial protection, 14-day battery life, continuous heart rate and SpO2 biometric tracking.',
    short_description: 'Aerospace titanium case, AMOLED, 14-day battery.',
    sku: 'ALI-TCH-005',
    brand: 'Titan Edge',
    price: 32000,
    discount_price: 27999,
    category_id: 'cat-1',
    stock_quantity: 9,
    low_stock_threshold: 4,
    is_active: true,
    is_featured: false,
    is_best_seller: true,
    is_new_arrival: true,
    rating: 4.9,
    review_count: 32,
    variants: ['Raw Titanium', 'Matte Midnight Space'],
    specifications: {
      'Display': '1.43" Super AMOLED 466x466',
      'Battery': '14 days typical usage',
      'Sensors': 'Optical heart rate, SpO2, Accelerometer, Barometer',
      'Water Rating': '5 ATM + IP68',
    },
    images: [
      {
        id: 'img-5-1',
        product_id: 'prod-5',
        image_url: '/src/assets/images/category_tech_gadgets_1790526605221.jpg',
        alt_text: 'Titan Smart Pulse Watch',
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date('2026-01-22').toISOString(),
    updated_at: new Date('2026-01-22').toISOString(),
  },
  {
    id: 'prod-6',
    name: 'Everyday Minimalist Leather Loafers',
    slug: 'everyday-minimalist-leather-loafers',
    description: 'Handcrafted full-grain calf leather upper with cushioned cork footbed and flexible stitched rubber sole. Sleek unlined collar for instant out-of-the-box comfort.',
    short_description: 'Full-grain calf leather, stitched sole, cushioned footbed.',
    sku: 'ALI-SHS-006',
    brand: 'Milano Craft',
    price: 12500,
    discount_price: 10500,
    category_id: 'cat-4',
    stock_quantity: 18,
    low_stock_threshold: 5,
    is_active: true,
    is_featured: false,
    is_best_seller: true,
    is_new_arrival: false,
    rating: 4.6,
    review_count: 22,
    variants: ['Espresso Brown (EU 41)', 'Espresso Brown (EU 42)', 'Espresso Brown (EU 43)', 'Onyx Black (EU 42)'],
    specifications: {
      'Upper': '100% Full-grain calfskin leather',
      'Lining': 'Breathable calfskin lining',
      'Sole': 'Flexible reinforced rubber',
      'Construction': 'Blake stitched',
    },
    images: [
      {
        id: 'img-6-1',
        product_id: 'prod-6',
        image_url: '/src/assets/images/hero_ali_store_showcase_1790526590148.jpg',
        alt_text: 'Minimalist Leather Loafers',
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date('2026-01-24').toISOString(),
    updated_at: new Date('2026-01-24').toISOString(),
  },
  {
    id: 'prod-7',
    name: 'Architectural Brushed Brass Table Lamp',
    slug: 'architectural-brushed-brass-table-lamp',
    description: 'Warm ambient glow through an opal frosted glass globe balanced upon a solid brushed brass pedestal. Features continuous stepless capacitive touch dimming.',
    short_description: 'Solid brushed brass, mouth-blown opal glass, touch dimmer.',
    sku: 'ALI-HOM-007',
    brand: 'Lumen Atelier',
    price: 9400,
    discount_price: 7999,
    category_id: 'cat-3',
    stock_quantity: 7,
    low_stock_threshold: 3,
    is_active: true,
    is_featured: true,
    is_best_seller: false,
    is_new_arrival: false,
    rating: 4.8,
    review_count: 17,
    variants: ['Brushed Brass', 'Anodized Matte Black'],
    specifications: {
      'Light Source': 'Integrated 2700K warm LED module',
      'Brightness': '600 Lumens stepless dimmable',
      'Cord': '1.8m braided textile cord',
      'Power': 'USB-C powered / 12W',
    },
    images: [
      {
        id: 'img-7-1',
        product_id: 'prod-7',
        image_url: '/src/assets/images/category_home_living_1790526633926.jpg',
        alt_text: 'Architectural Brass Table Lamp',
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date('2026-01-25').toISOString(),
    updated_at: new Date('2026-01-25').toISOString(),
  },
  {
    id: 'prod-8',
    name: 'Heavyweight Loopback French Terry Hoodie',
    slug: 'heavyweight-loopback-french-terry-hoodie',
    description: 'Cut from 480 GSM custom loopback organic cotton fleece. Features double-layered structural hood, ribbed side gussets, and seamless pouch pocket.',
    short_description: '480 GSM organic cotton, structured double hood.',
    sku: 'ALI-APL-008',
    brand: 'Atelier Ali',
    price: 7200,
    discount_price: undefined,
    category_id: 'cat-2',
    stock_quantity: 42,
    low_stock_threshold: 10,
    is_active: true,
    is_featured: false,
    is_best_seller: true,
    is_new_arrival: true,
    rating: 4.9,
    review_count: 36,
    variants: ['Heather Grey (M)', 'Heather Grey (L)', 'Oatmeal (M)', 'Oatmeal (L)', 'Jet Black (XL)'],
    specifications: {
      'Fabric': '480 GSM 100% GOTS Organic Cotton',
      'Fit': 'Boxy relaxed contemporary fit',
      'Finish': 'Pre-shrunk garment dye',
    },
    images: [
      {
        id: 'img-8-1',
        product_id: 'prod-8',
        image_url: '/src/assets/images/category_apparel_fashion_1790526618915.jpg',
        alt_text: 'Heavyweight French Terry Hoodie',
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date('2026-01-28').toISOString(),
    updated_at: new Date('2026-01-28').toISOString(),
  },
  {
    id: 'prod-9',
    name: 'Magnetic MagSafe 10000mAh Power Core',
    slug: 'magnetic-magsafe-10000mah-power-core',
    description: 'Ultra-slim CNC machined aluminum wireless power bank with 15W Qi2 fast wireless output and 30W USB-C Power Delivery. Snaps firmly onto smartphones with powerful neodymium magnets.',
    short_description: '15W wireless, 30W USB-C PD, aluminum unibody.',
    sku: 'ALI-TCH-009',
    brand: 'Apex Audio',
    price: 6500,
    discount_price: 5200,
    category_id: 'cat-1',
    stock_quantity: 35,
    low_stock_threshold: 6,
    is_active: true,
    is_featured: false,
    is_best_seller: false,
    is_new_arrival: true,
    rating: 4.7,
    review_count: 15,
    variants: ['Space Grey', 'Silver Frost'],
    specifications: {
      'Capacity': '10,000mAh (38.5Wh)',
      'Outputs': '15W Qi2 Wireless + 30W Type-C',
      'Thickness': '13.8mm ultra-slim',
    },
    images: [
      {
        id: 'img-9-1',
        product_id: 'prod-9',
        image_url: '/src/assets/images/category_tech_gadgets_1790526605221.jpg',
        alt_text: 'Magnetic Power Core 10000mAh',
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date('2026-01-30').toISOString(),
    updated_at: new Date('2026-01-30').toISOString(),
  },
  {
    id: 'prod-10',
    name: 'Full Grain Leather Bifold Cardholder',
    slug: 'full-grain-leather-bifold-cardholder',
    description: 'Vegetable-tanned full-grain leather wallet with beveled hand-burnished edges and RFID blocking protective foil. Holds up to 8 cards plus unfolded bank notes.',
    short_description: 'Vegetable tanned leather, RFID shielding, hand burnished.',
    sku: 'ALI-WTC-010',
    brand: 'Vanguard Horology',
    price: 3800,
    discount_price: 3100,
    category_id: 'cat-5',
    stock_quantity: 20,
    low_stock_threshold: 5,
    is_active: true,
    is_featured: false,
    is_best_seller: false,
    is_new_arrival: false,
    rating: 4.8,
    review_count: 18,
    variants: ['Whiskey Tan', 'Pitch Black', 'Forest Green'],
    specifications: {
      'Leather': 'Pueblo Vegetable Tanned Italian Cowhide',
      'Capacity': '6 card slots + 2 hidden compartments',
      'Dimensions': '10.5cm x 7.5cm',
    },
    images: [
      {
        id: 'img-10-1',
        product_id: 'prod-10',
        image_url: '/src/assets/images/hero_ali_store_showcase_1790526590148.jpg',
        alt_text: 'Leather Bifold Cardholder',
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date('2026-02-01').toISOString(),
    updated_at: new Date('2026-02-01').toISOString(),
  },
  {
    id: 'prod-11',
    name: 'CloudStrider Carbon Running Shoes',
    slug: 'cloudstrider-carbon-running-shoes',
    description: 'Elite marathon shoe featuring responsive supercritical foam midsole embedded with full-length articulated carbon fiber plate. Ultra-light engineered mesh upper for maximum breathability.',
    short_description: 'Full carbon plate, supercritical foam, 198g ultralight.',
    sku: 'ALI-SHS-011',
    brand: 'Milano Craft',
    price: 21500,
    discount_price: 18999,
    category_id: 'cat-4',
    stock_quantity: 14,
    low_stock_threshold: 4,
    is_active: true,
    is_featured: true,
    is_best_seller: false,
    is_new_arrival: true,
    rating: 4.9,
    review_count: 24,
    variants: ['Cloud White (42)', 'Cloud White (43)', 'Volt Neon (42)', 'Volt Neon (44)'],
    specifications: {
      'Weight': '198g (Men’s 42)',
      'Drop': '8mm offset',
      'Plate': 'Full-length 3K Carbon Fiber',
    },
    images: [
      {
        id: 'img-11-1',
        product_id: 'prod-11',
        image_url: '/src/assets/images/hero_ali_store_showcase_1790526590148.jpg',
        alt_text: 'CloudStrider Carbon Running Shoes',
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date('2026-02-03').toISOString(),
    updated_at: new Date('2026-02-03').toISOString(),
  },
  {
    id: 'prod-12',
    name: 'Raw Selvedge Japanese Denim Jeans',
    slug: 'raw-selvedge-japanese-denim-jeans',
    description: '14.5 oz red-line selvedge denim shuttle-loomed in Kojima, Japan. Pure indigo rope-dyed with copper rivets and button fly that will fade into a personalized patina over time.',
    short_description: '14.5 oz Japanese selvedge denim, redline shuttle loom.',
    sku: 'ALI-APL-012',
    brand: 'Atelier Ali',
    price: 11000,
    discount_price: 9200,
    category_id: 'cat-2',
    stock_quantity: 19,
    low_stock_threshold: 4,
    is_active: true,
    is_featured: false,
    is_best_seller: false,
    is_new_arrival: false,
    rating: 4.7,
    review_count: 12,
    variants: ['30 Waist', '32 Waist', '34 Waist', '36 Waist'],
    specifications: {
      'Weight': '14.5oz Unwashed Raw Denim',
      'Weave': 'Right-hand twill red-line selvedge',
      'Fit': 'Straight leg regular rise',
    },
    images: [
      {
        id: 'img-12-1',
        product_id: 'prod-12',
        image_url: '/src/assets/images/category_apparel_fashion_1790526618915.jpg',
        alt_text: 'Raw Selvedge Japanese Denim Jeans',
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date('2026-02-05').toISOString(),
    updated_at: new Date('2026-02-05').toISOString(),
  },
  {
    id: 'prod-13',
    name: 'Sculptural Marble Bookends (Set of 2)',
    slug: 'sculptural-marble-bookends-set',
    description: 'Solid Carrara marble cut and honed by hand into geometric arch bookends. Heavy weight provides sturdy support for heavy volumes while lending timeless architectural elegance.',
    short_description: 'Solid Carrara marble, honed matte touch, 3.2 kg pair.',
    sku: 'ALI-HOM-013',
    brand: 'Sora Ceramics',
    price: 6400,
    discount_price: undefined,
    category_id: 'cat-3',
    stock_quantity: 11,
    low_stock_threshold: 3,
    is_active: true,
    is_featured: false,
    is_best_seller: false,
    is_new_arrival: false,
    rating: 4.8,
    review_count: 9,
    variants: ['White Carrara Marble', 'Nero Marquina Black'],
    specifications: {
      'Weight': '3.2 kg total pair',
      'Dimensions': '16cm H x 10cm W x 8cm D',
      'Base': 'Felt padded anti-scratch base',
    },
    images: [
      {
        id: 'img-13-1',
        product_id: 'prod-13',
        image_url: '/src/assets/images/category_home_living_1790526633926.jpg',
        alt_text: 'Sculptural Marble Bookends',
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date('2026-02-08').toISOString(),
    updated_at: new Date('2026-02-08').toISOString(),
  },
  {
    id: 'prod-14',
    name: 'Precision Mechanical 75% Wireless Keyboard',
    slug: 'precision-mechanical-75-wireless-keyboard',
    description: 'Gasket-mounted mechanical keyboard with pre-lubed tactile switches, PBT double-shot keycaps, RGB backlighting, tri-mode connection (Bluetooth, 2.4GHz, and USB-C).',
    short_description: 'Gasket-mount, pre-lubed switches, tri-mode wireless.',
    sku: 'ALI-TCH-014',
    brand: 'Apex Audio',
    price: 16500,
    discount_price: 13999,
    category_id: 'cat-1',
    stock_quantity: 8,
    low_stock_threshold: 3,
    is_active: true,
    is_featured: false,
    is_best_seller: false,
    is_new_arrival: true,
    rating: 4.9,
    review_count: 27,
    variants: ['Tactile Brown Switches', 'Smooth Linear Red Switches'],
    specifications: {
      'Layout': '75% Compact (82 keys)',
      'Battery': '4000mAh lithium rechargeable',
      'Plate': 'Flex-cut polycarbonate plate',
    },
    images: [
      {
        id: 'img-14-1',
        product_id: 'prod-14',
        image_url: '/src/assets/images/category_tech_gadgets_1790526605221.jpg',
        alt_text: 'Precision Mechanical Wireless Keyboard',
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date('2026-02-10').toISOString(),
    updated_at: new Date('2026-02-10').toISOString(),
  },
  {
    id: 'prod-15',
    name: 'Handcrafted Suede Chelsea Boots',
    slug: 'handcrafted-suede-chelsea-boots',
    description: 'Italian waterproof suede with twin elastic side gussets, woven pull tabs, Goodyear-welted Dainite studded rubber sole for all-weather traction and effortless elegance.',
    short_description: 'Italian waterproof suede, Goodyear welted, Dainite sole.',
    sku: 'ALI-SHS-015',
    brand: 'Milano Craft',
    price: 18500,
    discount_price: 15500,
    category_id: 'cat-4',
    stock_quantity: 13,
    low_stock_threshold: 4,
    is_active: true,
    is_featured: true,
    is_best_seller: false,
    is_new_arrival: false,
    rating: 4.8,
    review_count: 16,
    variants: ['Snuff Suede (EU 41)', 'Snuff Suede (EU 42)', 'Snuff Suede (EU 43)', 'Dark Chocolate (EU 42)'],
    specifications: {
      'Upper': 'Water-repellent Italian reverse calf suede',
      'Welt': '360-degree storm welt',
      'Sole': 'British Dainite studded rubber',
    },
    images: [
      {
        id: 'img-15-1',
        product_id: 'prod-15',
        image_url: '/src/assets/images/hero_ali_store_showcase_1790526590148.jpg',
        alt_text: 'Handcrafted Suede Chelsea Boots',
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date('2026-02-12').toISOString(),
    updated_at: new Date('2026-02-12').toISOString(),
  },
  {
    id: 'prod-16',
    name: 'Waffle Knit Cashmere Wool Cardigan',
    slug: 'waffle-knit-cashmere-wool-cardigan',
    description: 'Blended with 70% extra-fine Merino wool and 30% Mongolian cashmere. Substantial 7-gauge waffle knit with genuine horn buttons and ribbed shawl collar.',
    short_description: 'Merino & Mongolian cashmere blend, 7-gauge waffle knit.',
    sku: 'ALI-APL-016',
    brand: 'Atelier Ali',
    price: 14200,
    discount_price: 12000,
    category_id: 'cat-2',
    stock_quantity: 6, // Low stock indicator!
    low_stock_threshold: 7,
    is_active: true,
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: false,
    rating: 5.0,
    review_count: 20,
    variants: ['Camel Heather (M)', 'Camel Heather (L)', 'Deep Charcoal (M)'],
    specifications: {
      'Blend': '70% Merino Wool, 30% Grade-A Cashmere',
      'Knit': '7-gauge dimensional waffle stitch',
      'Origin': 'Spun in Biella, Italy',
    },
    images: [
      {
        id: 'img-16-1',
        product_id: 'prod-16',
        image_url: '/src/assets/images/category_apparel_fashion_1790526618915.jpg',
        alt_text: 'Waffle Knit Cashmere Cardigan',
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
    ],
    created_at: new Date('2026-02-15').toISOString(),
    updated_at: new Date('2026-02-15').toISOString(),
  },
];

export const initialCoupons: Coupon[] = [
  {
    id: 'coup-1',
    code: 'ALI10',
    discount_type: 'percentage',
    discount_value: 10,
    minimum_order_amount: 3000,
    maximum_discount: 2000,
    usage_limit: 500,
    used_count: 42,
    expires_at: '2027-12-31T23:59:59Z',
    is_active: true,
    created_at: new Date('2026-01-01').toISOString(),
    updated_at: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'coup-2',
    code: 'SAVE500',
    discount_type: 'fixed',
    discount_value: 500,
    minimum_order_amount: 4000,
    usage_limit: 200,
    used_count: 18,
    expires_at: '2027-12-31T23:59:59Z',
    is_active: true,
    created_at: new Date('2026-01-01').toISOString(),
    updated_at: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'coup-3',
    code: 'WELCOME15',
    discount_type: 'percentage',
    discount_value: 15,
    minimum_order_amount: 5000,
    maximum_discount: 3000,
    usage_limit: 100,
    used_count: 67,
    expires_at: '2027-12-31T23:59:59Z',
    is_active: true,
    created_at: new Date('2026-01-01').toISOString(),
    updated_at: new Date('2026-01-01').toISOString(),
  },
];

export const initialStoreSettings: StoreSettings = {
  id: 'settings-1',
  store_name: 'Ali Online Store',
  logo_url: '',
  description: 'Curated direct-to-consumer destination for premium electronics, modern apparel, footwear, and architectural home living.',
  phone: '+92 300 1234567',
  email: 'support@alionlinestore.pk',
  whatsapp: '+923001234567',
  address: 'Suite 402, Ali Commercial Tower, Main Boulevard, Gulberg III, Lahore, Pakistan',
  business_hours: 'Monday – Saturday: 9:00 AM – 10:00 PM (PKT)',
  currency: 'PKR',
  currency_symbol: 'Rs.',
  delivery_fee: 250,
  free_delivery_threshold: 4000,
  social_links: {
    facebook: 'https://facebook.com/alionlinestore',
    instagram: 'https://instagram.com/alionlinestore',
    twitter: 'https://twitter.com/alionlinestore',
    youtube: 'https://youtube.com',
  },
  payment_instructions: {
    bank_transfer: 'Bank: Meezan Bank Ltd\nAccount Title: Ali Online Store (Pvt) Ltd\nAccount Number: 0284-0104928172\nIBAN: PK64MEZN0002840104928172',
    easypaisa: 'Account Title: Ali Store Official\nAccount Number: 0300-1234567',
    jazzcash: 'Account Title: Ali Store Official\nAccount Number: 0300-1234567',
  },
  created_at: new Date('2026-01-01').toISOString(),
  updated_at: new Date('2026-01-01').toISOString(),
};

export const initialReviews: Review[] = [
  {
    id: 'rev-1',
    product_id: 'prod-1',
    customer_id: 'demo-user-1',
    customer_name: 'Hamza Tariq',
    rating: 5,
    comment: 'The soundstage on these headphones is extraordinary. Deep bass without muddying the mids. Fast delivery to Karachi in 2 days.',
    is_approved: true,
    created_at: new Date('2026-02-14').toISOString(),
    updated_at: new Date('2026-02-14').toISOString(),
  },
  {
    id: 'rev-2',
    product_id: 'prod-1',
    customer_id: 'demo-user-2',
    customer_name: 'Zainab Bilal',
    rating: 5,
    comment: 'Packaging was immaculate. ANC blocks out office hum completely. Well worth every rupee.',
    is_approved: true,
    created_at: new Date('2026-02-18').toISOString(),
    updated_at: new Date('2026-02-18').toISOString(),
  },
  {
    id: 'rev-3',
    product_id: 'prod-3',
    customer_id: 'demo-user-3',
    customer_name: 'Usman Malik',
    rating: 5,
    comment: 'The linen quality is genuinely premium. Soft, breathable, and fits true to size with a subtle stylish drape.',
    is_approved: true,
    created_at: new Date('2026-02-20').toISOString(),
    updated_at: new Date('2026-02-20').toISOString(),
  },
  {
    id: 'rev-4',
    product_id: 'prod-4',
    customer_id: 'demo-user-4',
    customer_name: 'Ayesha Khan',
    rating: 5,
    comment: 'Looks like a sculpture from an architectural gallery. Arrived safely with plenty of cushioning.',
    is_approved: true,
    created_at: new Date('2026-02-22').toISOString(),
    updated_at: new Date('2026-02-22').toISOString(),
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ord-10025',
    order_number: 'ALI-10025',
    customer_id: 'demo-customer-1',
    subtotal: 21498,
    discount: 2149,
    delivery_fee: 0,
    total: 19349,
    payment_method: 'cash_on_delivery',
    payment_status: 'pending',
    status: 'processing',
    shipping_full_name: 'Farhan Siddiqui',
    shipping_phone: '+92 321 8492019',
    shipping_email: 'farhan.siddiqui@gmail.com',
    shipping_address: 'House 42-B, Street 14, Phase 5 DHA',
    shipping_area: 'DHA Phase 5',
    shipping_city: 'Lahore',
    shipping_postal_code: '54792',
    customer_notes: 'Please ring bell before delivering.',
    admin_notes: 'Confirmed via WhatsApp verification call.',
    courier: 'TCS Express',
    tracking_number: 'TCS-92817264',
    items: [
      {
        id: 'oi-1',
        order_id: 'ord-10025',
        product_id: 'prod-1',
        product_name: 'Apex Studio Wireless Headphones',
        product_image: '/src/assets/images/category_tech_gadgets_1790526605221.jpg',
        quantity: 1,
        unit_price: 15999,
        variant: 'Matte Black',
        created_at: new Date('2026-03-24T14:30:00Z').toISOString(),
      },
      {
        id: 'oi-2',
        order_id: 'ord-10025',
        product_id: 'prod-3',
        product_name: 'Pure Linen Relaxed Overshirt',
        product_image: '/src/assets/images/category_apparel_fashion_1790526618915.jpg',
        quantity: 1,
        unit_price: 5499,
        variant: 'Natural Ivory',
        created_at: new Date('2026-03-24T14:30:00Z').toISOString(),
      },
    ],
    created_at: new Date('2026-03-24T14:30:00Z').toISOString(),
    updated_at: new Date('2026-03-24T16:00:00Z').toISOString(),
  },
  {
    id: 'ord-10024',
    order_number: 'ALI-10024',
    customer_id: 'demo-customer-2',
    subtotal: 19500,
    discount: 500,
    delivery_fee: 0,
    total: 19000,
    payment_method: 'easypaisa',
    payment_status: 'paid',
    status: 'shipped',
    shipping_full_name: 'Bilal Ahmed',
    shipping_phone: '+92 333 4910283',
    shipping_email: 'bilal.ahmed@yahoo.com',
    shipping_address: 'Apartment 7-C, Clifton Palms, Block 4',
    shipping_area: 'Clifton',
    shipping_city: 'Karachi',
    shipping_postal_code: '75600',
    admin_notes: 'Payment verified on EasyPaisa TRX 98218731',
    courier: 'Leopards Courier',
    tracking_number: 'LCS-5829104',
    items: [
      {
        id: 'oi-3',
        order_id: 'ord-10024',
        product_id: 'prod-2',
        product_name: 'Vanguard Chronograph Classic Watch',
        product_image: '/src/assets/images/hero_ali_store_showcase_1790526590148.jpg',
        quantity: 1,
        unit_price: 19500,
        variant: 'Silver / Cognac',
        created_at: new Date('2026-03-22T10:15:00Z').toISOString(),
      },
    ],
    created_at: new Date('2026-03-22T10:15:00Z').toISOString(),
    updated_at: new Date('2026-03-23T11:00:00Z').toISOString(),
  },
  {
    id: 'ord-10023',
    order_number: 'ALI-10023',
    customer_id: 'demo-customer-3',
    subtotal: 7999,
    discount: 0,
    delivery_fee: 0,
    total: 7999,
    payment_method: 'bank_transfer',
    payment_status: 'paid',
    status: 'delivered',
    shipping_full_name: 'Sara Naeem',
    shipping_phone: '+92 301 7728192',
    shipping_email: 'sara.naeem@hotmail.com',
    shipping_address: 'House 19, Street 8, F-7/2',
    shipping_area: 'F-7/2',
    shipping_city: 'Islamabad',
    shipping_postal_code: '44000',
    admin_notes: 'Delivered successfully on March 21.',
    courier: 'TCS Express',
    tracking_number: 'TCS-11928374',
    items: [
      {
        id: 'oi-4',
        order_id: 'ord-10023',
        product_id: 'prod-7',
        product_name: 'Architectural Brushed Brass Table Lamp',
        product_image: '/src/assets/images/category_home_living_1790526633926.jpg',
        quantity: 1,
        unit_price: 7999,
        variant: 'Brushed Brass',
        created_at: new Date('2026-03-18T09:00:00Z').toISOString(),
      },
    ],
    created_at: new Date('2026-03-18T09:00:00Z').toISOString(),
    updated_at: new Date('2026-03-21T15:30:00Z').toISOString(),
  },
  {
    id: 'ord-10022',
    order_number: 'ALI-10022',
    customer_id: 'demo-customer-4',
    subtotal: 10500,
    discount: 0,
    delivery_fee: 0,
    total: 10500,
    payment_method: 'cash_on_delivery',
    payment_status: 'pending',
    status: 'pending',
    shipping_full_name: 'Kamran Raza',
    shipping_phone: '+92 345 8829102',
    shipping_email: 'kamran.raza@gmail.com',
    shipping_address: 'House 88, Street 3, Cavalry Ground',
    shipping_area: 'Cavalry Ground',
    shipping_city: 'Lahore',
    shipping_postal_code: '54810',
    items: [
      {
        id: 'oi-5',
        order_id: 'ord-10022',
        product_id: 'prod-6',
        product_name: 'Everyday Minimalist Leather Loafers',
        product_image: '/src/assets/images/hero_ali_store_showcase_1790526590148.jpg',
        quantity: 1,
        unit_price: 10500,
        variant: 'Espresso Brown (EU 42)',
        created_at: new Date('2026-03-26T18:00:00Z').toISOString(),
      },
    ],
    created_at: new Date('2026-03-26T18:00:00Z').toISOString(),
    updated_at: new Date('2026-03-26T18:00:00Z').toISOString(),
  },
];
